// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Achievement struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Chill struct {
	ID             string      `json:"id"`
	StartTimestamp string      `json:"startTimestamp"`
	EndTimestamp   *string     `json:"endTimestamp,omitempty"`
	Coordinate     *Coordinate `json:"coordinate"`
}

type Coordinate struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CoordinateInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type EndChillInput struct {
	ID        string `json:"id"`
	Timestamp string `json:"timestamp"`
}

type StartChillInput struct {
	Coordinate *CoordinateInput `json:"coordinate"`
	Timestamp  string           `json:"timestamp"`
}

type User struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Achievements []*Achievement `json:"achievements,omitempty"`
	Chills       []*Chill       `json:"chills,omitempty"`
}
