// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Achievements     string
	Chills           string
	Photos           string
	TracePoints      string
	UserAchievements string
	UserChills       string
	Users            string
}{
	Achievements:     "achievements",
	Chills:           "chills",
	Photos:           "photos",
	TracePoints:      "trace_points",
	UserAchievements: "user_achievements",
	UserChills:       "user_chills",
	Users:            "users",
}
