// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserChill is an object representing the database table.
type UserChill struct {
	ID      string `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID  string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ChillID string `boil:"chill_id" json:"chill_id" toml:"chill_id" yaml:"chill_id"`

	R *userChillR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userChillL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserChillColumns = struct {
	ID      string
	UserID  string
	ChillID string
}{
	ID:      "id",
	UserID:  "user_id",
	ChillID: "chill_id",
}

var UserChillTableColumns = struct {
	ID      string
	UserID  string
	ChillID string
}{
	ID:      "user_chills.id",
	UserID:  "user_chills.user_id",
	ChillID: "user_chills.chill_id",
}

// Generated where

var UserChillWhere = struct {
	ID      whereHelperstring
	UserID  whereHelperstring
	ChillID whereHelperstring
}{
	ID:      whereHelperstring{field: "\"user_chills\".\"id\""},
	UserID:  whereHelperstring{field: "\"user_chills\".\"user_id\""},
	ChillID: whereHelperstring{field: "\"user_chills\".\"chill_id\""},
}

// UserChillRels is where relationship names are stored.
var UserChillRels = struct {
	Chill string
	User  string
}{
	Chill: "Chill",
	User:  "User",
}

// userChillR is where relationships are stored.
type userChillR struct {
	Chill *Chill `boil:"Chill" json:"Chill" toml:"Chill" yaml:"Chill"`
	User  *User  `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*userChillR) NewStruct() *userChillR {
	return &userChillR{}
}

func (r *userChillR) GetChill() *Chill {
	if r == nil {
		return nil
	}
	return r.Chill
}

func (r *userChillR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// userChillL is where Load methods for each relationship are stored.
type userChillL struct{}

var (
	userChillAllColumns            = []string{"id", "user_id", "chill_id"}
	userChillColumnsWithoutDefault = []string{"user_id", "chill_id"}
	userChillColumnsWithDefault    = []string{"id"}
	userChillPrimaryKeyColumns     = []string{"id"}
	userChillGeneratedColumns      = []string{}
)

type (
	// UserChillSlice is an alias for a slice of pointers to UserChill.
	// This should almost always be used instead of []UserChill.
	UserChillSlice []*UserChill
	// UserChillHook is the signature for custom UserChill hook methods
	UserChillHook func(context.Context, boil.ContextExecutor, *UserChill) error

	userChillQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userChillType                 = reflect.TypeOf(&UserChill{})
	userChillMapping              = queries.MakeStructMapping(userChillType)
	userChillPrimaryKeyMapping, _ = queries.BindMapping(userChillType, userChillMapping, userChillPrimaryKeyColumns)
	userChillInsertCacheMut       sync.RWMutex
	userChillInsertCache          = make(map[string]insertCache)
	userChillUpdateCacheMut       sync.RWMutex
	userChillUpdateCache          = make(map[string]updateCache)
	userChillUpsertCacheMut       sync.RWMutex
	userChillUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userChillAfterSelectHooks []UserChillHook

var userChillBeforeInsertHooks []UserChillHook
var userChillAfterInsertHooks []UserChillHook

var userChillBeforeUpdateHooks []UserChillHook
var userChillAfterUpdateHooks []UserChillHook

var userChillBeforeDeleteHooks []UserChillHook
var userChillAfterDeleteHooks []UserChillHook

var userChillBeforeUpsertHooks []UserChillHook
var userChillAfterUpsertHooks []UserChillHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserChill) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserChill) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserChill) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserChill) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserChill) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserChill) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserChill) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserChill) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserChill) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userChillAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserChillHook registers your hook function for all future operations.
func AddUserChillHook(hookPoint boil.HookPoint, userChillHook UserChillHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userChillAfterSelectHooks = append(userChillAfterSelectHooks, userChillHook)
	case boil.BeforeInsertHook:
		userChillBeforeInsertHooks = append(userChillBeforeInsertHooks, userChillHook)
	case boil.AfterInsertHook:
		userChillAfterInsertHooks = append(userChillAfterInsertHooks, userChillHook)
	case boil.BeforeUpdateHook:
		userChillBeforeUpdateHooks = append(userChillBeforeUpdateHooks, userChillHook)
	case boil.AfterUpdateHook:
		userChillAfterUpdateHooks = append(userChillAfterUpdateHooks, userChillHook)
	case boil.BeforeDeleteHook:
		userChillBeforeDeleteHooks = append(userChillBeforeDeleteHooks, userChillHook)
	case boil.AfterDeleteHook:
		userChillAfterDeleteHooks = append(userChillAfterDeleteHooks, userChillHook)
	case boil.BeforeUpsertHook:
		userChillBeforeUpsertHooks = append(userChillBeforeUpsertHooks, userChillHook)
	case boil.AfterUpsertHook:
		userChillAfterUpsertHooks = append(userChillAfterUpsertHooks, userChillHook)
	}
}

// One returns a single userChill record from the query.
func (q userChillQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserChill, error) {
	o := &UserChill{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for user_chills")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserChill records from the query.
func (q userChillQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserChillSlice, error) {
	var o []*UserChill

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to UserChill slice")
	}

	if len(userChillAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserChill records in the query.
func (q userChillQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count user_chills rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userChillQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if user_chills exists")
	}

	return count > 0, nil
}

// Chill pointed to by the foreign key.
func (o *UserChill) Chill(mods ...qm.QueryMod) chillQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChillID),
	}

	queryMods = append(queryMods, mods...)

	return Chills(queryMods...)
}

// User pointed to by the foreign key.
func (o *UserChill) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadChill allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userChillL) LoadChill(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserChill interface{}, mods queries.Applicator) error {
	var slice []*UserChill
	var object *UserChill

	if singular {
		var ok bool
		object, ok = maybeUserChill.(*UserChill)
		if !ok {
			object = new(UserChill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserChill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserChill))
			}
		}
	} else {
		s, ok := maybeUserChill.(*[]*UserChill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserChill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserChill))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userChillR{}
		}
		args = append(args, object.ChillID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userChillR{}
			}

			for _, a := range args {
				if a == obj.ChillID {
					continue Outer
				}
			}

			args = append(args, obj.ChillID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`chills`),
		qm.WhereIn(`chills.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Chill")
	}

	var resultSlice []*Chill
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Chill")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chills")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chills")
	}

	if len(chillAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Chill = foreign
		if foreign.R == nil {
			foreign.R = &chillR{}
		}
		foreign.R.UserChills = append(foreign.R.UserChills, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChillID == foreign.ID {
				local.R.Chill = foreign
				if foreign.R == nil {
					foreign.R = &chillR{}
				}
				foreign.R.UserChills = append(foreign.R.UserChills, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userChillL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserChill interface{}, mods queries.Applicator) error {
	var slice []*UserChill
	var object *UserChill

	if singular {
		var ok bool
		object, ok = maybeUserChill.(*UserChill)
		if !ok {
			object = new(UserChill)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserChill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserChill))
			}
		}
	} else {
		s, ok := maybeUserChill.(*[]*UserChill)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserChill)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserChill))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userChillR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userChillR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserChills = append(foreign.R.UserChills, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserChills = append(foreign.R.UserChills, local)
				break
			}
		}
	}

	return nil
}

// SetChill of the userChill to the related item.
// Sets o.R.Chill to related.
// Adds o to related.R.UserChills.
func (o *UserChill) SetChill(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Chill) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_chills\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"chill_id"}),
		strmangle.WhereClause("\"", "\"", 2, userChillPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChillID = related.ID
	if o.R == nil {
		o.R = &userChillR{
			Chill: related,
		}
	} else {
		o.R.Chill = related
	}

	if related.R == nil {
		related.R = &chillR{
			UserChills: UserChillSlice{o},
		}
	} else {
		related.R.UserChills = append(related.R.UserChills, o)
	}

	return nil
}

// SetUser of the userChill to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserChills.
func (o *UserChill) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_chills\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userChillPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userChillR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserChills: UserChillSlice{o},
		}
	} else {
		related.R.UserChills = append(related.R.UserChills, o)
	}

	return nil
}

// UserChills retrieves all the records using an executor.
func UserChills(mods ...qm.QueryMod) userChillQuery {
	mods = append(mods, qm.From("\"user_chills\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_chills\".*"})
	}

	return userChillQuery{q}
}

// FindUserChill retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserChill(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserChill, error) {
	userChillObj := &UserChill{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_chills\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userChillObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from user_chills")
	}

	if err = userChillObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userChillObj, err
	}

	return userChillObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserChill) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_chills provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userChillColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userChillInsertCacheMut.RLock()
	cache, cached := userChillInsertCache[key]
	userChillInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userChillAllColumns,
			userChillColumnsWithDefault,
			userChillColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userChillType, userChillMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userChillType, userChillMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_chills\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_chills\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into user_chills")
	}

	if !cached {
		userChillInsertCacheMut.Lock()
		userChillInsertCache[key] = cache
		userChillInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserChill.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserChill) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userChillUpdateCacheMut.RLock()
	cache, cached := userChillUpdateCache[key]
	userChillUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userChillAllColumns,
			userChillPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update user_chills, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_chills\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userChillPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userChillType, userChillMapping, append(wl, userChillPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update user_chills row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for user_chills")
	}

	if !cached {
		userChillUpdateCacheMut.Lock()
		userChillUpdateCache[key] = cache
		userChillUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userChillQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for user_chills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for user_chills")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserChillSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userChillPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_chills\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userChillPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in userChill slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all userChill")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserChill) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_chills provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userChillColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userChillUpsertCacheMut.RLock()
	cache, cached := userChillUpsertCache[key]
	userChillUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userChillAllColumns,
			userChillColumnsWithDefault,
			userChillColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userChillAllColumns,
			userChillPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert user_chills, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userChillPrimaryKeyColumns))
			copy(conflict, userChillPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_chills\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userChillType, userChillMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userChillType, userChillMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert user_chills")
	}

	if !cached {
		userChillUpsertCacheMut.Lock()
		userChillUpsertCache[key] = cache
		userChillUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserChill record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserChill) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no UserChill provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userChillPrimaryKeyMapping)
	sql := "DELETE FROM \"user_chills\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from user_chills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for user_chills")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userChillQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no userChillQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from user_chills")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_chills")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserChillSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userChillBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userChillPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_chills\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userChillPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from userChill slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_chills")
	}

	if len(userChillAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserChill) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserChill(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserChillSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserChillSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userChillPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_chills\".* FROM \"user_chills\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userChillPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in UserChillSlice")
	}

	*o = slice

	return nil
}

// UserChillExists checks if the UserChill row exists.
func UserChillExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_chills\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if user_chills exists")
	}

	return exists, nil
}

// Exists checks if the UserChill row exists.
func (o *UserChill) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserChillExists(ctx, exec, o.ID)
}
